controller_list:
  - name: fake_manipulator_controller
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
initial:  # Define initial robot poses.
  - group: manipulator
    pose: home